OrgGroup:
    type: entity
    table: org_group
    indexes:
        fk_org_group_org1_idx:
            columns:
                - passport_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        intro:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 描述
    manyToOne:
        passport:
            targetEntity: Org
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                passport_id:
                    referencedColumnName: passport_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
