OrgServiceAttr:
    type: entity
    table: org_service_attr
    indexes:
        IDX_83C85CEF6800E622:
            columns:
                - org_service_id
    id:
        serviceAttrCode:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            id: true
            column: service_attr_code
    fields:
        v:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    oneToOne:
        orgService:
            targetEntity: OrgService
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                org_service_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
